### ISSUE TITLE
BC端绑定qq机器人未响应QQ群信息

### ISSUE THREAD

**Issue by Jfeng666** [DreamVoid/Link2QQ#4]
**问题描述**

在1.18 paperspigot服务端中使用link2qq绑定QQ，机器人对群内消息无反应
已用miral指令在服务器群发送消息，机器人正常上线且可发送接收信息

**复现方法**

Minecraft 服务端(lobby)版本：PaperSpigot-1.18
BC-waterfall最新
Link2QQ-Bungee 插件版本：1.1
MiraiMC-Bungee 插件版本：1.5.1
进入服务器输入/link2qq bind qq号
复制信息输入到Q群
机器人无响应

**登陆的机器人也是2878256218下面日志可看，群号无误**
**link2QQ-config**
> bot:
  bot-accounts:
    - 2878256218
  group-ids:
    - 160659544
  add-bind-command: "添加绑定"
  confirm-bind-command: "确认绑定"
  confirm-code-length: 6

**游戏日志**

> [23:42:04] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[23:42:11] [Render thread/INFO]: [STDOUT]: New minimap session initialized!
[23:42:11] [Render thread/INFO]: [STDOUT]: New world map session initialized!
[23:42:11] [Render thread/INFO]: Started 2 worker threads
[23:42:11] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:42:12] [Render thread/INFO]: Destroying pipeline OVERWORLD
[23:42:12] [Render thread/INFO]: Creating pipeline OVERWORLD
[23:42:12] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[23:42:12] [Render thread/WARN]: [gbuffers_textured] Unsupported uniform: (unknown:35669) blendFunc
[23:42:12] [Render thread/WARN]: [gbuffers_textured_color] Unsupported uniform: (unknown:35669) blendFunc
[23:42:13] [Render thread/WARN]: [gbuffers_particles] Unsupported uniform: (unknown:35669) blendFunc
[23:42:14] [Render thread/INFO]: [CHAT] _jfeng加入了游戏
[23:42:14] [Render thread/INFO]: Loaded 21 advancements
[23:42:32] [Render thread/INFO]: [CHAT] 请使用你的QQ私聊机器人或向机器人所在群发送以下消息：
[23:42:32] [Render thread/INFO]: [CHAT] §b确认绑定 _jfeng 8qX1IX
[23:42:32] [Render thread/INFO]: [CHAT] 以完成验证流程 (点击可复制)
[23:43:53] [Render thread/INFO]: [CHAT] [Server: 正在关闭服务器]
[23:43:53] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[23:43:53] [Render thread/INFO]: [STDOUT]: Finalizing world map session...
[23:43:53] [Thread-1/INFO]: [STDOUT]: World map force-cleaned!
[23:43:53] [Render thread/INFO]: [STDOUT]: World map session finalized.
[23:43:53] [Render thread/INFO]: Stopping worker threads

**paper端日志**
> [23:42:11] [Server thread/INFO]: _jfeng joined the game
[23:42:12] [Server thread/INFO]: _jfeng[/127.0.0.1:64472] logged in with entity id 422 at ([world]-1.109905498065641, 102.0, 1.7434064103967768)
[23:43:53] [Server thread/INFO]: Stopping the server
[23:43:53] [Server thread/INFO]: Stopping server
[23:43:53] [Server thread/INFO]: Saving players
[23:43:53] [Server thread/INFO]: _jfeng lost connection: Server closed
[23:43:53] [Server thread/INFO]: _jfeng left the game

**waterfall日志**
> [23:40:18] [main/INFO]: Using standard Java JCE cipher.
[23:40:18] [main/INFO]: Using standard Java compressor.
[23:40:18] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462
[23:40:18] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
[23:40:18] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
[23:40:18] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
[23:40:18] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
[23:40:18] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
[23:40:18] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
[23:40:19] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:19] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:21] [main/INFO] [MiraiMC]: Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[23:40:21] [main/INFO] [MiraiMC]: Verifying mirai-core-all-2.9.0-M1.jar
[23:40:22] [main/INFO] [MiraiMC]: Loading library mirai-core-all-2.9.0-M1.jar
[23:40:22] [main/INFO]: Loaded plugin MiraiMC version 1.5.1 by DreamVoid
[23:40:22] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:22] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:22] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:22] [main/INFO]: Loaded plugin Link2QQ version 1.1 by DreamVoid
[23:40:22] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:22] [main/WARN]: Forced host server pvp is not defined
[23:40:22] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:22] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:22] [main/INFO] [MiraiMC]: Mirai working dir: default
[23:40:22] [main/INFO] [MiraiMC]: Starting Mirai-Events listener.
[23:40:22] [main/INFO] [MiraiMC]: Registering commands.
[23:40:22] [main/INFO] [MiraiMC]: Loading auto-login file.
[23:40:22] [main/INFO] [MiraiMC]: Initializing SQLite database.
[23:40:22] [MiraiMC Pool Thread #0/INFO] [MiraiMC]: [AutoLogin] Starting auto login task.
[23:40:22] [MiraiMC Pool Thread #0/INFO] [MiraiMC]: [AutoLogin] Auto login bot account: 2878256218 Protocol: ANDROID_PHONE
[23:40:22] [MiraiMC Pool Thread #0/INFO] [MiraiMC]: 登录新的机器人账号: 2878256218, 协议: ANDROID_PHONE
[23:40:23] [main/INFO] [MiraiMC]: Initializing bStats metrics.
[23:40:23] [main/WARN] [MiraiMC]: 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[23:40:23] [main/WARN] [MiraiMC]: 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[23:40:23] [main/INFO] [MiraiMC]: All tasks done. Welcome to use MiraiMC!
[23:40:23] [main/INFO]: Enabled plugin MiraiMC version 1.5.1 by DreamVoid
[23:40:23] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:23] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:23] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:23] [main/INFO]: Enabled plugin Link2QQ version 1.1 by DreamVoid
[23:40:23] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[23:40:23] [MiraiMC Pool Thread #1/INFO] [MiraiMC]: Checking update...
[23:40:26] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25565
[23:40:26] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Server list: 36.155.202.141:14000, 120.232.196.151:8080, 36.155.248.239:80, 120.232.19.199:8080, msfwifi.3g.qq.com:8080, 39.156.126.247:80, 111.30.187.249:80, 211.136.109.25:8080, 120.232.130.13:443, 111.30.187.201:80.
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:168)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:163)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:111)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: Caused by: java.util.jar.JarException: file:/E:/gametool/mc/服务器/server/1.18/bc-test/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.9.0-M1.jar has unsigned entries - net/mamoe/mirai/internal/MiraiImplKt.class
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
[23:40:29] [DefaultDispatcher-worker-1/ERROR]: 	... 39 more
[23:40:29] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Loaded account secrets from local cache.
[23:40:29] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: ECDH key is valid.
[23:40:30] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Saved account secrets to local cache for fast login.
[23:40:30] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Login successful.
[23:40:30] [nioEventLoopGroup-2-3/INFO] [MiraiMC]: Server time updated, serverTime: 1638459630, diff: 0ms=0.0s
[23:40:30] [DefaultDispatcher-worker-4/INFO] [MiraiMC]: Syncing friend message history...
[23:40:30] [DefaultDispatcher-worker-4/INFO] [MiraiMC]: Start loading friend list...
[23:40:30] [DefaultDispatcher-worker-3/INFO] [MiraiMC]: Start loading stranger list...
[23:40:30] [DefaultDispatcher-worker-4/INFO] [MiraiMC]: Start loading group list...
[23:40:30] [DefaultDispatcher-worker-4/INFO] [MiraiMC]: Successfully loaded stranger list: 0 in total
[23:40:30] [DefaultDispatcher-worker-4/INFO] [MiraiMC]: No OtherClient online.
[23:40:30] [DefaultDispatcher-worker-3/INFO] [MiraiMC]: Successfully loaded friend list: 2 in total
[23:40:30] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Syncing friend message history: Success.
[23:40:30] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Successfully loaded group list: 1 in total.
[23:40:30] [DefaultDispatcher-worker-5/INFO] [MiraiMC]: Scheduled refresh login session in 19d 23h 55min 0.0s.
[23:40:30] [DefaultDispatcher-worker-4/INFO] [MiraiMC]: Scheduled key refresh in 23h 55min 0.0s.
[23:40:30] [DefaultDispatcher-worker-1/INFO] [MiraiMC]: Bot login successful.
[23:40:30] [MiraiMC Pool Thread #0/INFO] [MiraiMC]: 风清扬(2878256218) 登录成功
[23:41:24] [MiraiMC Pool Thread #1/WARN] [MiraiMC]: An error occurred while fetching the latest version, reason: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
[23:42:02] [Netty Worker IO Thread #0/INFO]: [/127.0.0.1:64460] <-> InitialHandler has pinged
[23:42:03] [Netty Worker IO Thread #1/INFO]: [/127.0.0.1:64463] <-> InitialHandler has pinged
[23:42:04] [Netty Worker IO Thread #2/INFO]: [/127.0.0.1:64466] <-> InitialHandler has connected
[23:42:11] [Netty Worker IO Thread #2/INFO]: [_jfeng|/127.0.0.1:64466] <-> ServerConnector [lobby] has connected
[23:43:53] [Netty Worker IO Thread #2/INFO]: [_jfeng] disconnected with: Server closed
[23:43:53] [Netty Worker IO Thread #2/INFO]: [/127.0.0.1:64466|_jfeng] -> UpstreamBridge has disconnected
[23:43:53] [Netty Worker IO Thread #2/INFO]: [/127.0.0.1:64466|_jfeng] <-> DownstreamBridge <-> [lobby] has disconnected
[23:43:57] [Shutdown Thread/INFO]: Closing listener [id: 0x5a4712de, L:/0:0:0:0:0:0:0:0:25565]
[23:43:57] [Shutdown Thread/INFO]: Closing pending connections
[23:43:57] [Shutdown Thread/INFO]: Disconnecting 0 connections
[23:43:58] [Shutdown Thread/INFO]: Disabling plugins
[23:43:58] [Shutdown Thread/INFO] [MiraiMC]: Stopping bot event listener.
[23:43:58] [Shutdown Thread/INFO] [MiraiMC]: Closing all bots
[23:43:58] [Shutdown Thread/INFO] [MiraiMC]: Closing all bots
[23:43:58] [Shutdown Thread/INFO] [MiraiMC]: Closing SQLite database.
[23:43:58] [DefaultDispatcher-worker-5/INFO] [MiraiMC]: Bot cancelled: Job was cancelled
[23:43:58] [Shutdown Thread/INFO] [MiraiMC]: All tasks done. Thanks for use MiraiMC!
[23:43:58] [Shutdown Thread/INFO]: Closing IO threads
[23:44:00] [Shutdown Thread/INFO]: Thank you and goodbye

**Comment by DreamVoid** [comment]
所以你是获取到绑定消息以后马上把服务器关了？
